Added solution
Nokafan/hibernate-cinema pull request #3
Opened 2020-10-07 17:19 UTC by Nokafan

2020-10-07 18:44 UTC, DariiaPikul requested changes

2020-10-07 18:44 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/dao/impl/GenericDaoImpl.java
> +            throw new DataProcessingExeption("Can't insert entity " + entity.toString(), e);
toString() method will be called by default

2020-10-07 18:44 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +                            + "WHERE u.email = :email", User.class)
```suggestion
            return session.createQuery("FROM User u WHERE u.email = :email", User.class)
```

2020-10-07 18:44 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +    UserService userService;
Access modifiers

2020-10-07 18:44 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +                && !email.isEmpty() && !password.isEmpty()) {
?

2020-10-07 18:47 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +    }
Why overriding this method since we don't change a thing?

2020-10-08 07:07 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +        if (!email.isEmpty() && !password.isEmpty()) {
we will take of validation later on, let's remove this check for now

2020-10-08 07:07 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +        String saltedPassword = HashUtil.hashPassword(password, user.getSalt());
```suggestion
        String hashedPassword = HashUtil.hashPassword(password, user.getSalt());
```

2020-10-08 07:07 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +    private boolean idPassworValid(User user, String password) {
```suggestion
    private boolean isPassworValid(User user, String password) {
```

2020-10-08 07:07 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/exeption/AuthenticationException.java
> +public class AuthenticationException extends RuntimeException {
checklist

2020-10-08 07:07 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +            throw new DataProcessingExeption("Faild to get user email = " + email, e);
```suggestion
            throw new DataProcessingExeption("Faild to get user with email = " + email, e);
```

2020-10-08 09:46 UTC, RomanDubovskyi approved these changes

2020-10-08 09:47 UTC, merged